<?php

namespace App\Http\Requests;


use App\IntegrationHub\Contracts\IPropertyProvider;
use App\Rules\Occupancy;
use Illuminate\Validation\Rule;

class SearchAvailabilityFormRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'check_in'=>'required|date|date_format:Y-m-d',
            'check_out'=>'required|date|date_format:Y-m-d|after:check_in',
            'providers'=>[
                'array',
                Rule::in([
                    IPropertyProvider::SABRE_PROPERTY_PROVIDER
                ])
            ],
            'latitude'=>'required_without:location',
            'longitude'=>'required_without:location',
            'location'=>'sometimes|string',
            'radius'=>'integer|max:100|min:1', // default=5miles
            'units'=>[
                'sometimes',
                'required',
                'string',
                Rule::in(['MI','KM']) // default=MI
            ],
            'currency'=>'exists:currencies,code',
            'occupancy'=>['required','array',new Occupancy()],
            'amenities'=>'array',
            'min_price'=>'integer',
            'max_price'=>'integer'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }
}
